version: '3.6'
services:
  pddb_test:
    container_name: pgdb_build_it_2022
    image: postgres:10.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
  
  mysql-202:
    container_name: mysql_build_it_2022
    image: mysql:latest
    restart: always
    ports:
      - "3302:3306"
    expose:
      - "3302"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data-mysql:/var/lib/mysql

  mysql-203-A:
    container_name: mysql_build_it_2022
    image: mysql:latest
    restart: always
    ports:
      - "3303:3306"
    expose:
      - "3303"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data-mysql:/var/lib/mysql

  mysql-203-B:
    container_name: mysql_build_it_2022
    image: mysql:latest
    restart: always
    ports:
      - "3304:3306"
    expose:
      - "3304"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data-mysql:/var/lib/mysql

  mysql-203-C:
    container_name: mysql_build_it_2022
    image: mysql:latest
    restart: always
    ports:
      - "3305:3306"
    expose:
      - "3305"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data-mysql:/var/lib/mysql

  mysql-101:
    container_name: mysql_build_it_2022
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data-mysql:/var/lib/mysql

  sqlpad:
    container_name: sqlpad_build_it_2022
    image: "sqlpad/sqlpad:6"
    restart: always
    ports:
      - 3001:3000
    environment:
      - SQLPAD_ADMIN=${ADMIN_USERNAME}
      - SQLPAD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /mnt/sqlpad:/var/lib/sqlpad

volumes:
  db-data:
  db-data-mysql:
